layout_spectrum: 0.4892473
typography_spectrum: 0.5268817
color:
  saturation: 0.394302
  lightness: 0.7124975
  brandStrength: 0.7741935
  brandColors:
    - '#FFFFFF'
    - '#384043'
    - '#000000'
    - '#727374'
    - '#C5C5C5'
  rhythmicContrast: 0.3837537
name: Perimeter1
